### ISSUE TITLE
Feature request: free crop

### ISSUE THREAD

**Issue by kronik** [SurpriseWave/SWImageRotation#1]
Could you please add a free crop tool? Something like [TOCropViewController](https://github.com/TimOliver/TOCropViewController).

**Comment by SurpriseWave** [comment]
Hi kronik thanks to take interest in our work. Your suggestion is to add free crop is nice but not suitable for this library. This library is for rotation not for cropping. Most image editing tool give cropping and rotating as different options. So we are not going to add this kind of cropping in this code but in future we may creates different library for this.
